import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronRight, Heart, Plus, Sparkles, X } from 'lucide-react'
import './styles.css'

type DateType = 'coffee' | 'dinner' | 'walk' | 'movie'
type Status = 'CREATED' | 'ACCEPTED' | 'DECLINED'
type Experience = { occasion?: string; question?: string; intro?: string; dates?: string[]; activities?: DateType[]; place?: string; theme?: 'rose' | 'sunset' | 'night' }
type Invite = { id: string; senderName: string; receiverName: string; dateType: DateType; proposedDate?: string; customMessage?: string; status: Status; experience?: Experience; qrCodeDataUrl?: string; ownerUrl?: string; expiresAt?: string }
type InviteStatus = { id: string; status: Status; responseDetails?: Record<string, string>; viewCount: number; updatedAt: string }
const API = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080').replace(/\/$/, '')
const ACT: Record<DateType, [string, string]> = { coffee: ['☕', 'Qahva ichish'], dinner: ['🍝', 'Kechki ovqat'], walk: ['🌿', 'Sayr qilish'], movie: ['🎬', 'Kinoga borish'] }
const OCC = ['Birinchi uchrashuv', 'Yillik sana', 'Seni sog‘indim', 'Yarashib olish', 'Shunchaki, chunki sen']
async function api<T>(url: string, init?: RequestInit): Promise<T> { const r = await fetch(API + url, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } }); if (!r.ok) { const b = await r.json().catch(() => null); throw new Error(b?.message || 'So‘rov bajarilmadi.') } return r.json() }
const msg = (e: unknown) => e instanceof Error ? e.message : 'Nimadir xato ketdi.'
const date = (s: string) => new Intl.DateTimeFormat('uz-UZ', { weekday: 'long', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' }).format(new Date(s))
const calendarLink = (title: string, startsAt: string, location = '') => { const stamp = (value: Date) => value.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, ''); const start = new Date(startsAt); const end = new Date(start.getTime() + 60 * 60 * 1000); return `data:text/calendar;charset=utf-8,${encodeURIComponent(`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${stamp(start)}\nDTEND:${stamp(end)}\nSUMMARY:${title}\nLOCATION:${location}\nEND:VEVENT\nEND:VCALENDAR`)}` }
function Header() { return <header><a href="/" className="brand">uchrashamizmi<span>✦</span></a><small>Uchrashuvlar unutilmas bo‘lsin</small></header> }
function Steps({ n }: { n: number }) { return <div className="steps">{['Ism', 'Taklif', 'Sana', 'Faoliyat', 'Tayyor'].map((x, i) => <div className={i < n ? 'on' : ''} key={x}><b>{i + 1 < n ? <Check size={11} /> : i + 1}</b><small>{x}</small></div>)}</div> }

function Create() {
  const [n, setN] = useState(1), [err, setErr] = useState(''), [busy, setBusy] = useState(false), [made, setMade] = useState<Invite | null>(null)
  const [d, setD] = useState({ receiver: '', sender: '', senderEmail: '', occasion: OCC[0], customOccasion: '', theme: 'rose' as Experience['theme'], question: 'Men bilan uchrashuvga borasanmi?', intro: '', dateInput: '', dates: [] as string[], activities: ['coffee'] as DateType[], place: '' })
  const set = <K extends keyof typeof d>(k: K, v: typeof d[K]) => setD(x => ({ ...x, [k]: v }))
  const next = () => { if (n === 1 && !d.receiver.trim()) return setErr('Ismni kiriting.'); if (n === 2 && (!d.sender.trim() || !d.senderEmail.trim())) return setErr('Ismingiz va email manzilingizni kiriting.'); setErr(''); setN(x => x + 1) }
  const addDate = () => { if (!d.dateInput) return; const x = new Date(d.dateInput).toISOString(); if (!d.dates.includes(x)) set('dates', [...d.dates, x]); set('dateInput', '') }
  const toggle = (x: DateType) => set('activities', d.activities.includes(x) ? d.activities.filter(y => y !== x) : [...d.activities, x])
  async function make() { setBusy(true); try { const experience: Experience = { occasion: d.occasion, question: d.question, intro: d.intro, dates: d.dates, activities: d.activities, place: d.place, theme: d.theme }; setMade(await api<Invite>('/api/v1/invitations', { method: 'POST', body: JSON.stringify({ senderName: d.sender, senderEmail: d.senderEmail, receiverName: d.receiver, dateType: d.activities[0] || 'coffee', proposedDate: d.dates[0] || null, customMessage: d.intro || null, experience }) })) } catch (e) { setErr(msg(e)) } finally { setBusy(false) } }
  if (made) return <Share invite={made} />
  return <main className="maker"><Header /><section className="intro"><div className="tag"><Sparkles size={14} /> SHAXSIY TAKLIF</div><h1>Oddiy “kelasanmi?”<br /><em>yetarli emas.</em></h1><p>Unga kichik bir lahza yarating.</p></section><section className="box"><Steps n={n} />
    {n === 1 && <div className="form"><i>01 / BOSHLAYMIZ</i><h2>Uning ismi nima?</h2><p>Unga qanday murojaat qilasiz?</p><input autoFocus value={d.receiver} maxLength={100} onChange={e => set('receiver', e.target.value)} placeholder="Masalan, Madina" /><Preview name={d.receiver || 'Madina'} /></div>}
    {n === 2 && <div className="form"><i>02 / TAKLIF</i><h2>Kayfiyatni belgilang</h2><label>Sabab yoki bahona</label><div className="occasion">{OCC.map(x => <button className={x === d.occasion ? 'selected' : ''} onClick={() => { set('occasion', x); set('customOccasion', '') }} key={x}>{x}</button>)}<button className={d.customOccasion ? 'selected' : ''} onClick={() => set('occasion', d.customOccasion || 'Boshqa sabab')}>+ Boshqa</button></div><input value={d.customOccasion} maxLength={120} onChange={e => { set('customOccasion', e.target.value); if (e.target.value.trim()) set('occasion', e.target.value) }} placeholder="O‘zingizning sababingizni yozing..." /><label>Taklif uslubi</label><div className="theme-choice">{([['rose', '🌸 Romantik'], ['sunset', '☀️ Iliq'], ['night', '🌙 Kechki']] as const).map(([key, label]) => <button className={d.theme === key ? 'selected' : ''} onClick={() => set('theme', key)} key={key}>{label}</button>)}</div><label>Sizning ismingiz</label><input value={d.sender} maxLength={100} onChange={e => set('sender', e.target.value)} placeholder="Masalan, Aziz" /><label>Javob keladigan Gmail</label><input type="email" value={d.senderEmail} maxLength={254} onChange={e => set('senderEmail', e.target.value)} placeholder="siz@gmail.com" /><small className="email-help">U “ha” deganda, tanlovlari va PDF-chipta shu manzilga keladi.</small><label>Asosiy savol</label><input value={d.question} maxLength={180} onChange={e => set('question', e.target.value)} /><label>Yurakdan xabar <small>(ixtiyoriy)</small></label><textarea value={d.intro} maxLength={2000} onChange={e => set('intro', e.target.value)} placeholder="Seni ko‘rishni juda xohlardim..." /></div>}
    {n === 3 && <div className="form"><i>03 / SANA VA VAQT</i><h2>U tanlashi uchun vaqtlar</h2><p>Kamida bitta variant qo‘shing yoki vaqtni keyin kelishing.</p><div className="add"><input type="datetime-local" min={new Date().toISOString().slice(0, 16)} value={d.dateInput} onChange={e => set('dateInput', e.target.value)} /><button onClick={addDate}><Plus /></button></div><div className="chips">{d.dates.map((x, i) => <button onClick={() => set('dates', d.dates.filter((_, j) => j !== i))} key={x}><CalendarDays size={14} />{date(x)}<X size={14} /></button>)}</div></div>}
    {n === 4 && <div className="form"><i>04 / UCHRASHUV</i><h2>Nimalar qilasiz?</h2><p>Bir yoki bir nechta variant tanlang.</p><div className="activity">{(Object.keys(ACT) as DateType[]).map(x => <button onClick={() => toggle(x)} className={d.activities.includes(x) ? 'selected' : ''} key={x}><span>{ACT[x][0]}</span><b>{ACT[x][1]}</b>{d.activities.includes(x) && <Check size={14} />}</button>)}</div><label>Joy <small>(ixtiyoriy)</small></label><input value={d.place} onChange={e => set('place', e.target.value)} placeholder="Masalan, Magic City yoki sevimli qahvaxona" /></div>}
    {n === 5 && <div className="form final"><b className="emoji">💌</b><i>05 / TAYYOR</i><h2>Yuborishga tayyor</h2><p><b>{d.receiver}</b> taklifni havola orqali ochadi, “ha” deydi va o‘ziga qulay variantni tanlaydi.</p><div className="summary"><span>{d.occasion}</span><span>{d.activities.map(x => ACT[x][0]).join(' ')}</span>{d.dates[0] && <span>{date(d.dates[0])}</span>}</div></div>}
    {err && <div className="error">{err}</div>}<div className="actions">{n > 1 ? <button className="back" onClick={() => setN(n - 1)}><ArrowLeft size={16} /> Ortga</button> : <span />}{n < 5 ? <button className="primary" onClick={next}>Davom etish <ArrowRight size={16} /></button> : <button className="primary" disabled={busy} onClick={make}>{busy ? 'Yaratilmoqda...' : <>Taklif yaratish <Heart size={16} fill="currentColor" /></>}</button>}</div>
  </section></main>
}
function Preview({ name }: { name: string }) { return <div className="preview"><small>JONLI PREVIEW</small><b>💌</b><strong>{name}, men bilan<br />uchrashuvga borasanmi?</strong><button>Ha, albatta ♡</button></div> }
function Share({ invite }: { invite: Invite }) { const [copied, setCopied] = useState(false), url = `${location.origin}/invite/${invite.id}`; const ownerPath = invite.ownerUrl ? `${location.origin}${new URL(invite.ownerUrl).pathname}${new URL(invite.ownerUrl).search}` : ''; async function copy() { await navigator.clipboard.writeText(url); setCopied(true); setTimeout(() => setCopied(false), 1600) } return <main className="share"><Header /><section><div className="done"><Check /></div><i>TAYYOR!</i><h1>Endi navbat <em>unda.</em></h1><p>Havolani {invite.receiverName}ga yuboring. Qolganini taklifingiz hal qiladi.</p><div className="shareurl"><input readOnly value={url} /><button onClick={copy}>{copied ? 'Nusxalandi' : 'Nusxalash'}</button></div>{invite.qrCodeDataUrl && <div className="qr-card"><div className="qr-glow"></div><img src={invite.qrCodeDataUrl} alt="Taklif QR kodi" /><b>QR orqali oching</b><small>{invite.receiverName} uchun maxsus taklif</small></div>}<a className="pdf-download" href={`${API}/api/v1/invitations/${invite.id}/pdf`} download="uchrashamizmi-taklif.pdf">↓ PDF taklifnomani yuklash</a><div className="owner-link">{ownerPath && <a href={ownerPath}>Javoblarni kuzatish →</a>}<a href="/">Yana taklif yaratish</a></div></section></main> }

function Choice({ title, detail, choices, chosen, setChosen, done }: { title: string; detail: string; choices: string[]; chosen: string; setChosen: (x: string) => void; done: () => void }) { return <div className="choice"><div className="round">♡</div><i>YARIM YO‘L QOLDI</i><h2>{title}</h2><p>{detail}</p><div>{choices.length ? choices.map(x => <button onClick={() => setChosen(x)} className={chosen === x ? 'selected' : ''} key={x}>{x}<Check size={16} /></button>) : <small>Variantlar keyin kelishiladi ✦</small>}</div><button className="primary" disabled={!!choices.length && !chosen} onClick={done}>Davom etish <ChevronRight size={17} /></button></div> }
function MultiChoice({ title, detail, choices, selected, setSelected, done }: { title: string; detail: string; choices: string[]; selected: string[]; setSelected: (x: string[]) => void; done: () => void }) { const toggle = (x: string) => setSelected(selected.includes(x) ? selected.filter(y => y !== x) : [...selected, x]); return <div className="choice"><div className="round">♡</div><i>YARIM YO‘L QOLDI</i><h2>{title}</h2><p>{detail}</p><div>{choices.map(x => <button onClick={() => toggle(x)} className={selected.includes(x) ? 'selected' : ''} key={x}>{x}<Check size={16} /></button>)}</div><small className="multi-hint">Bir nechta variant tanlashingiz mumkin</small><button className="primary" disabled={!selected.length} onClick={done}>Davom etish <ChevronRight size={17} /></button></div> }
function Celebration() { return <div className="celebration" aria-hidden="true">{['💖', '✨', '💕', '✦', '💗', '✨', '♥', '💫', '💖', '✦', '💕', '✨'].map((x, i) => <span key={i}>{x}</span>)}</div> }
function Guest({ id }: { id: string }) {
  const [invite, setInvite] = useState<Invite | null>(null), [screen, setScreen] = useState<'ask' | 'date' | 'activity' | 'ticket'>('ask'), [selectedDate, setDate] = useState(''), [selectedActivity, setActivity] = useState<string[]>([]), [pos, setPos] = useState([0, 0]), [plea, setPlea] = useState(0), [err, setErr] = useState('')
  useEffect(() => { api<Invite>(`/api/v1/invitations/${id}`).then(x => { setInvite(x); if (x.status !== 'CREATED') setScreen('ticket') }).catch(e => setErr(msg(e))) }, [id])
  if (err) return <main className="guest"><Header /><section className="missing"><Heart /><h2>Taklif topilmadi</h2><p>{err}</p><a href="/">Bosh sahifaga qaytish</a></section></main>
  if (!invite) return <main className="guest"><Header /><p className="loading">Taklif ochilmoqda <span /></p></main>
  const exp = invite.experience || {}, dates = exp.dates || (invite.proposedDate ? [invite.proposedDate] : []), acts = exp.activities || [invite.dateType], question = exp.question || 'Men bilan uchrashuvga borasanmi?'
  async function confirm() { try { await api(`/api/v1/invitations/${id}/respond`, { method: 'POST', body: JSON.stringify({ status: 'ACCEPTED', responseDetails: { selectedDate, selectedActivity: selectedActivity.join(', '), place: exp.place || null } }) }); setScreen('ticket') } catch (e) { setErr(msg(e)) } }
  const pleas = [question, 'Iltimos, chiqaylik 🥺', 'Bir imkon bering, juda xursand bo‘laman ✨', 'Bir piyola qahva, xolos ☕', 'Oxirgi marta so‘rayapman: rostdan ham yo‘qmi?']
  const dodgeNo = () => { setPos([(Math.random() - .5) * 210, (Math.random() - .5) * 100]); setPlea(x => Math.min(x + 1, pleas.length - 1)) }
  return <main className="guest"><Header /><section className={`card theme-${exp.theme || 'rose'}`}>{screen === 'ask' && <><div className="letter">💌</div><i>{invite.senderName}dan sizga</i><h1>{invite.receiverName},<br />{pleas[plea]}</h1>{exp.occasion && <span className="pill">{exp.occasion}</span>}{exp.intro && <blockquote>“{exp.intro}”</blockquote>}<p className="soft">Yuragingiz nima deyapti? ✦</p><div className="answer-buttons"><button className="primary yes-answer" onClick={() => setScreen(dates.length ? 'date' : 'activity')}><Heart size={18} fill="currentColor" /> Ha, albatta!</button><button className="no" style={{ transform: `translate(${pos[0]}px,${pos[1]}px)` }} onPointerEnter={dodgeNo} onClick={dodgeNo}>{plea === 0 ? 'Yo‘q' : 'Yo‘q... deb bo‘lmaydi'}</button></div></>}
    {screen === 'date' && <Choice title="Qaysi vaqt sizga qulay?" detail="Sizning tanlovingizni kutmoqda" choices={dates.map(date)} chosen={selectedDate ? date(selectedDate) : ''} setChosen={x => setDate(dates.find(y => date(y) === x) || '')} done={() => setScreen('activity')} />}
    {screen === 'activity' && <MultiChoice title="Qanday uchrashuv bo‘lsin?" detail={exp.place ? `Joy: ${exp.place}` : 'Bir yoki bir nechta variant tanlang'} choices={acts.map(x => `${ACT[x][0]} ${ACT[x][1]}`)} selected={selectedActivity} setSelected={setActivity} done={confirm} />}
    {screen === 'ticket' && <div className="ticket"><Celebration /><div className="confetti">♥ ✦ ♥ ✦ ♥</div><div className="round victory-heart"><Heart fill="currentColor" /></div><i>UCHRASHUV TASDIQLANDI</i><h2>Bu — ha!</h2><p className="victory-text">Endi bu kichik hikoyaning eng yaxshi qismi boshlanadi.</p><p>Javobingiz {invite.senderName}ga yuborildi.</p><div>{selectedActivity.map(x => <span key={x}>{x}</span>)}{selectedDate && <span>{date(selectedDate)}</span>}{exp.place && <span>{exp.place}</span>}</div>{selectedDate && <a className="ticket-action" href={calendarLink(`Uchrashamizmi — ${invite.senderName} va ${invite.receiverName}`, selectedDate, exp.place)} download="uchrashuv.ics">Kalendarimga qo‘shish</a>}{exp.place && <a className="ticket-action" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(exp.place)}`}>Xaritada ochish</a>}<b>DATE-{id.slice(0, 8).toUpperCase()}</b></div>}</section></main>
}
function Owner({ id, token }: { id: string; token: string }) { const [status, setStatus] = useState<InviteStatus | null>(null), [error, setError] = useState(''); useEffect(() => { let timer: number; const load = () => api<InviteStatus>(`/api/v1/invitations/${id}/status?token=${encodeURIComponent(token)}`).then(setStatus).catch(e => setError(msg(e))); load(); timer = window.setInterval(load, 7000); return () => window.clearInterval(timer) }, [id, token]); if (error) return <main className="guest"><Header /><section className="missing"><Heart /><h2>Status sahifasi topilmadi</h2><p>{error}</p></section></main>; if (!status) return <main className="guest"><Header /><p className="loading">Status yuklanmoqda <span /></p></main>; const accepted = status.status === 'ACCEPTED'; return <main className="guest"><Header /><section className="owner-card"><i>SHAXSIY STATUS</i><h1>{accepted ? 'U “ha” dedi! 💕' : status.status === 'DECLINED' ? 'Javob keldi' : 'Taklifingiz yo‘lda'}</h1><p>{status.status === 'CREATED' ? `Hozircha ${status.viewCount} marta ochilgan. Sahifa avtomatik yangilanadi.` : 'Tanlovlar quyida.'}</p><div className="status-dot"><b>{status.status === 'CREATED' ? 'KUTILMOQDA' : accepted ? 'QABUL QILINDI' : 'RAD ETILDI'}</b></div>{status.responseDetails && Object.keys(status.responseDetails).length > 0 && <div className="response-data">{Object.entries(status.responseDetails).map(([key, value]) => <p key={key}><small>{key}</small><b>{String(value)}</b></p>)}</div>}</section></main> }
function App() { const invite = location.pathname.match(/^\/invite\/([^/]+)$/), owner = location.pathname.match(/^\/owner\/([^/]+)$/); return owner ? <Owner id={owner[1]} token={new URLSearchParams(location.search).get('token') || ''} /> : invite ? <Guest id={invite[1]} /> : <Create /> } createRoot(document.getElementById('root')!).render(<App />)
